"""
Template definitions for agent interactions.
This module provides common templates for agent prompts, feedback formats, and responses.
"""

try:
    # Try standard import in production
    from backend.agents.templates.coach_templates import (
        ANALYSIS_TEMPLATE,
        TIPS_TEMPLATE,
        SUMMARY_TEMPLATE,
        TEMPLATE_PROMPT,
        STAR_EVALUATION_TEMPLATE,
        PERFORMANCE_ANALYSIS_TEMPLATE,
        COMMUNICATION_ASSESSMENT_TEMPLATE,
        COMPLETENESS_EVALUATION_TEMPLATE,
        PERSONALIZED_FEEDBACK_TEMPLATE,
        PERFORMANCE_METRICS_TEMPLATE,
        FEEDBACK_TEMPLATES,
        GENERAL_ADVICE_TEMPLATE,
        STAR_METHOD_ADVICE_TEMPLATE,
        SYSTEM_PROMPT as COACH_SYSTEM_PROMPT,
        PRACTICE_QUESTION_PROMPT,
        PRACTICE_QUESTION_RESPONSE_TEMPLATE
    )
    from backend.agents.templates.interviewer_templates import (
        SYSTEM_PROMPT as INTERVIEWER_SYSTEM_PROMPT,
        QUESTION_TEMPLATE,
        EVALUATION_TEMPLATE,
        SUMMARY_TEMPLATE,
        QUALITY_ASSESSMENT_TEMPLATE,
        FOLLOW_UP_TEMPLATE,
        THINK_TEMPLATE,
        REASON_TEMPLATE,
        PLANNING_TEMPLATE,
        JOB_SPECIFIC_TEMPLATE,
        INTRODUCTION_TEMPLATES,
        ANSWER_EVALUATION_TEMPLATE,
        RESPONSE_FORMAT_TEMPLATE
    )
    from backend.agents.templates.skill_templates import (
        SYSTEM_PROMPT as SKILL_SYSTEM_PROMPT,
        SKILL_EXTRACTION_TEMPLATE,
        PROFICIENCY_ASSESSMENT_TEMPLATE,
        RESOURCE_SUGGESTION_TEMPLATE,
        SKILL_PROFILE_TEMPLATE,
        ASSESSMENT_RESPONSE_TEMPLATE,
        RECENT_ANSWER_ASSESSMENT_TEMPLATE,
        SKILL_UPDATE_NOTIFICATION_TEMPLATE
    )
except ImportError:
    # Use relative imports for development/testing
    from .coach_templates import (
        ANALYSIS_TEMPLATE,
        TIPS_TEMPLATE,
        SUMMARY_TEMPLATE,
        TEMPLATE_PROMPT,
        STAR_EVALUATION_TEMPLATE,
        PERFORMANCE_ANALYSIS_TEMPLATE,
        COMMUNICATION_ASSESSMENT_TEMPLATE,
        COMPLETENESS_EVALUATION_TEMPLATE,
        PERSONALIZED_FEEDBACK_TEMPLATE,
        PERFORMANCE_METRICS_TEMPLATE,
        FEEDBACK_TEMPLATES,
        GENERAL_ADVICE_TEMPLATE,
        STAR_METHOD_ADVICE_TEMPLATE,
        SYSTEM_PROMPT as COACH_SYSTEM_PROMPT,
        PRACTICE_QUESTION_PROMPT,
        PRACTICE_QUESTION_RESPONSE_TEMPLATE
    )
    from .interviewer_templates import (
        SYSTEM_PROMPT as INTERVIEWER_SYSTEM_PROMPT,
        QUESTION_TEMPLATE,
        EVALUATION_TEMPLATE,
        SUMMARY_TEMPLATE,
        QUALITY_ASSESSMENT_TEMPLATE,
        FOLLOW_UP_TEMPLATE,
        THINK_TEMPLATE,
        REASON_TEMPLATE,
        PLANNING_TEMPLATE,
        JOB_SPECIFIC_TEMPLATE,
        INTRODUCTION_TEMPLATES,
        ANSWER_EVALUATION_TEMPLATE,
        RESPONSE_FORMAT_TEMPLATE
    )
    from .skill_templates import (
        SYSTEM_PROMPT as SKILL_SYSTEM_PROMPT,
        SKILL_EXTRACTION_TEMPLATE,
        PROFICIENCY_ASSESSMENT_TEMPLATE,
        RESOURCE_SUGGESTION_TEMPLATE,
        SKILL_PROFILE_TEMPLATE,
        ASSESSMENT_RESPONSE_TEMPLATE,
        RECENT_ANSWER_ASSESSMENT_TEMPLATE,
        SKILL_UPDATE_NOTIFICATION_TEMPLATE
    )

__all__ = [
    # Coach templates
    'ANALYSIS_TEMPLATE',
    'TIPS_TEMPLATE',
    'SUMMARY_TEMPLATE',
    'TEMPLATE_PROMPT',
    'STAR_EVALUATION_TEMPLATE',
    'PERFORMANCE_ANALYSIS_TEMPLATE',
    'COMMUNICATION_ASSESSMENT_TEMPLATE',
    'COMPLETENESS_EVALUATION_TEMPLATE',
    'PERSONALIZED_FEEDBACK_TEMPLATE',
    'PERFORMANCE_METRICS_TEMPLATE',
    'FEEDBACK_TEMPLATES',
    'GENERAL_ADVICE_TEMPLATE',
    'STAR_METHOD_ADVICE_TEMPLATE',
    'COACH_SYSTEM_PROMPT',
    'PRACTICE_QUESTION_PROMPT',
    'PRACTICE_QUESTION_RESPONSE_TEMPLATE',
    
    # Interviewer templates
    'INTERVIEWER_SYSTEM_PROMPT',
    'QUESTION_TEMPLATE',
    'EVALUATION_TEMPLATE',
    'SUMMARY_TEMPLATE',
    'QUALITY_ASSESSMENT_TEMPLATE',
    'FOLLOW_UP_TEMPLATE',
    'THINK_TEMPLATE',
    'REASON_TEMPLATE',
    'PLANNING_TEMPLATE',
    'JOB_SPECIFIC_TEMPLATE',
    'INTRODUCTION_TEMPLATES',
    'ANSWER_EVALUATION_TEMPLATE',
    'RESPONSE_FORMAT_TEMPLATE',
    
    # Skill assessor templates
    'SKILL_SYSTEM_PROMPT',
    'SKILL_EXTRACTION_TEMPLATE',
    'PROFICIENCY_ASSESSMENT_TEMPLATE',
    'RESOURCE_SUGGESTION_TEMPLATE',
    'SKILL_PROFILE_TEMPLATE',
    'ASSESSMENT_RESPONSE_TEMPLATE',
    'RECENT_ANSWER_ASSESSMENT_TEMPLATE',
    'SKILL_UPDATE_NOTIFICATION_TEMPLATE'
] 